meta:
  version: "1.1.0"

llm:
  default_modes:
    action_decision: "normal"
    long_term_objective: "normal"
    nickname: "normal"
    single_choice: "normal"
    relation_resolver: "fast"
    story_teller: "fast"
    interaction_feedback: "fast"
    history_influence: "normal"

paths:
  templates: static/templates/
  game_configs: static/game_configs/
  saves: assets/saves/

ai:
  max_concurrent_requests: 10
  max_parse_retries: 3

game:
  init_npc_num: 9
  sect_num: 3 # init_npc_num大于sect_num时，会随机选择sect_num个宗门
  npc_awakening_rate_per_month: 0.01
  fortune_probability: 0.005
  misfortune_probability: 0.005
  gathering:
    auction_trigger_count: 1

df:
  ids_separator: ";"

avatar:
  persona_num: 3
  # all 引入所有主角不引入随机角色
  # random，正常随机角色，但是有一定概率出主角
  # none, 不引入主角（默认选项）
  protagonist: "random"

social:
  major_event_context_num: 10  # 大事（长期记忆）展示数量
  minor_event_context_num: 10  # 小事（短期记忆）展示数量
  relation_check_threshold: 5 # 关系检查需要的交互次数

nickname:
  major_event_threshold: 3  # 获得绰号需要的长期事件数量
  minor_event_threshold: 25  # 获得绰号需要的短期事件数量

save:
  max_events_to_save: 1000

frontend:
  water_speed: low
  cloud_freq: low