meta:
  version: "1.0.7"

llm:
  # 填入litellm支持的model name和key
  key: "your-api-key" # 目前需要的是阿里的qwen api
  model_name: "openai/qwen-plus"
  fast_model_name: "openai/qwen-flash"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"

paths:
  templates: static/templates/
  game_configs: static/game_configs/
  saves: assets/saves/

ai:
  max_decide_num: 3
  max_parse_retries: 3

game:
  init_npc_num: 12
  sect_num: 3 # init_npc_num大于sect_num时，会随机选择sect_num个宗门
  npc_birth_rate_per_month: 0.01
  fortune_probability: 0.005

df:
  ids_separator: ";"

avatar:
  persona_num: 3
  # all 引入所有主角不引入随机角色
  # random，正常随机角色，但是有一定概率出主角
  # none, 不引入主角（默认选项）
  protagonist: "all"

social:
  major_event_context_num: 10  # 大事（长期记忆）展示数量
  minor_event_context_num: 10  # 小事（短期记忆）展示数量

nickname:
  major_event_threshold: 5  # 获得绰号需要的长期事件数量
  minor_event_threshold: 25  # 获得绰号需要的短期事件数量

save:
  max_events_to_save: 1000

frontend:
  water_speed: low
  cloud_freq: low