meta:
  version: "1.0.3"

llm:
  # 填入litellm支持的model name和key
  key: "your-api-key" # 目前需要的是阿里的qwen api
  model_name: "openai/qwen-plus"
  fast_model_name: "openai/qwen-flash"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"

paths:
  templates: static/templates/
  game_configs: static/game_configs/
  saves: assets/saves/

ai:
  max_decide_num: 4
  max_parse_retries: 3

game:
  init_npc_num: 6
  sect_num: 2 # init_npc_num大于sect_num时，会随机选择sect_num个宗门
  npc_birth_rate_per_month: 0.001
  fortune_probability: 0.001

df:
  ids_separator: ";"

avatar:
  persona_num: 3

social:
  major_event_context_num: 10  # 大事（长期记忆）展示数量
  minor_event_context_num: 10  # 小事（短期记忆）展示数量

nickname:
  major_event_threshold: 10  # 获得绰号需要的长期事件数量
  minor_event_threshold: 50  # 获得绰号需要的短期事件数量

save:
  max_events_to_save: 1000

# defined_avatar:
#   surname: 丰川
#   given_name: 祥子
#   level: 31
#   age: 18
#   gender: 女
#   sect: 百兽宗
#   appearance: 10
#   personas:
#     - 穿越者
#     - 随性
#     - 外向
#   treasure: 百兽驭兽符
